# DataFrame
- A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table. Each column in a DataFrame can be thought of as a Series, and the entire DataFrame can be thought of as a collection of Series that share the same index.

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'Salary': [70000, 80000, 90000, 100000]
}

In [3]:
data_frame = pd.DataFrame(data)
print(data_frame)

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [7]:
data_list = [
    ['Alice', 25, 'New York', 70000],
    ['Bob', 30, 'Los Angeles', 80000],
    ['Charlie', 35, 'Chicago', 90000],
    ['David', 40, 'Houston', 100000]
]
columns=['Name', 'Age', 'City', 'Salary']
data_frame = pd.DataFrame(data_list)
data_frame2 = pd.DataFrame(data_list, columns=columns)
print(data_frame)
print("\nDataFrame with columns \n")
print(data_frame2)

         0   1            2       3
0    Alice  25     New York   70000
1      Bob  30  Los Angeles   80000
2  Charlie  35      Chicago   90000
3    David  40      Houston  100000

DataFrame with columns

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

## Selecting/ Indexing Colums

In [8]:
data_frame2["Name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [9]:
data_frame2[['Name','City']]

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

## Adding a Colums

In [25]:
data_frame2['Designation']  = ['Reciptionist','Teacher','Athlete','Plumber']
print(data_frame2)

      Name  Age         City   Designation
0    Alice   25     New York  Reciptionist
1      Bob   30  Los Angeles       Teacher
2  Charlie   35      Chicago       Athlete
3    David   40      Houston       Plumber

## Removing Columns

In [ ]:
data_frame2.drop('Designation', axis=1) #  Won't change the original data frame just a view
# Axis = 1 for columns and axis = 0 for rows

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [20]:
data_frame2.drop(['Salary','Designation'], axis=1, inplace=True) # Wiil modify the original data frame
print(data_frame2)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## Selecting Rows

In [22]:
data_frame2.loc[0] # Selecting the first row

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [23]:
data_frame2.loc[[0,2]] # Selecting the first and third row

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

In [24]:
data_frame2.iloc[0] # Selecting the first row using index

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

## Selecting portions of the DataFrame

In [26]:
data_frame2.loc[[0,1],['Name','City']] # Selecting specific rows and columns

    Name         City
0  Alice     New York
1    Bob  Los Angeles

In [29]:
data_frame2.loc[[2,3],['City','Designation']] # Selecting specific rows and columns

      City Designation
2  Chicago     Athlete
3  Houston     Plumber

## Conditional Selection

In [ ]:
# Select where age is greater than 30
data_frame2[data_frame2['Age'] > 30]

      Name  Age     City Designation
2  Charlie   35  Chicago     Athlete
3    David   40  Houston     Plumber

In [32]:
# Select where age is greater than 30 and city is Chicago
data_frame2[(data_frame2['Age'] > 30) & (data_frame2['City'] == 'Chicago')]

      Name  Age     City Designation
2  Charlie   35  Chicago     Athlete