# Joining dataframes

In [10]:
import numpy as np
import pandas as pd

In [27]:

users = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
})

print(users)

user_cities = pd.DataFrame({
    'id': [1, 2, 3, 6,7],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})
print(user_cities)

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
   id         city
0   1     New York
1   2  Los Angeles
2   3      Chicago
3   6      Houston
4   7      Phoenix

In [28]:
pd.merge(users, user_cities, on='id', how='inner')

   id     name         city
0   1    Alice     New York
1   2      Bob  Los Angeles
2   3  Charlie      Chicago

In [29]:
pd.merge(users, user_cities, on='id', how='outer')

   id     name         city
0   1    Alice     New York
1   2      Bob  Los Angeles
2   3  Charlie      Chicago
3   4    David          NaN
4   5      Eve          NaN
5   6      NaN      Houston
6   7      NaN      Phoenix

In [31]:
pd.merge(users, user_cities, on='id', how='left')

   id     name         city
0   1    Alice     New York
1   2      Bob  Los Angeles
2   3  Charlie      Chicago
3   4    David          NaN
4   5      Eve          NaN

In [32]:
pd.merge(users, user_cities, on='id', how='right')

   id     name         city
0   1    Alice     New York
1   2      Bob  Los Angeles
2   3  Charlie      Chicago
3   6      NaN      Houston
4   7      NaN      Phoenix

## Concatenation
Concatenation is the process of combining two or more dataframes along a particular axis (either rows or columns). In pandas, you can use the `pd.concat()` function to concatenate dataframes.

In [36]:
fruits = pd.DataFrame({
    'color': ['Red', 'Yellow', 'Orange'],
    'fruit': ['Apple', 'Banana', 'Mango']
})
fruits1 = pd.DataFrame({
    'color': ['Red', 'Yellow', 'Green'],
    'fruit': ['Apple', 'Banana', 'Kiwi']
})

In [ ]:
pd.concat([fruits,fruits1])

    color   fruit
0     Red   Apple
1  Yellow  Banana
2  Orange   Mango
0     Red   Apple
1  Yellow  Banana
2   Green    Kiwi

In [38]:
pd.concat([fruits,fruits1], axis=1)

    color   fruit   color   fruit
0     Red   Apple     Red   Apple
1  Yellow  Banana  Yellow  Banana
2  Orange   Mango   Green    Kiwi

## Joining

In [40]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4]) 

df1
df2

   score
2     85
3     90
4     75

In [41]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [42]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0