# Missing data 
- Find missing data and fill it with a specific value or drop the rows/columns with missing data.

In [4]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', np.nan, 'Charlie', 'David'],
    'Age': [25, 30, np.nan, 40],
    'City': ['New York', 'Los Angeles', np.nan, np.nan],
    'Designation': [np.nan, 'Manager', 'Analyst', 'Director']
}

In [6]:
df = pd.DataFrame(data) 
print(df)

      Name   Age         City Designation
0    Alice  25.0     New York         NaN
1      NaN  30.0  Los Angeles     Manager
2  Charlie   NaN          NaN     Analyst
3    David  40.0          NaN    Director

In [ ]:
df.isna() # Check for missing values

    Name    Age   City  Designation
0  False  False  False         True
1   True  False  False        False
2  False   True   True        False
3  False  False   True        False

In [9]:
df.isna().sum() # Count non-missing values in each column

Name           1
Age            1
City           2
Designation    1
dtype: int64

In [11]:
df.isnull() # Check for missing values
df.isna().any() # Check if any missing values exist in the DataFrame

Name           True
Age            True
City           True
Designation    True
dtype: bool

## Removing missing data

In [12]:
df.dropna() # Drop rows with missing values

Empty DataFrame
Columns: [Name, Age, City, Designation]
Index: []

In [13]:
df.dropna(thresh=3) # Drop rows with less than 3 non-missing values

    Name   Age         City Designation
0  Alice  25.0     New York         NaN
1    NaN  30.0  Los Angeles     Manager
3  David  40.0          NaN    Director

## Filling missing data

In [14]:
df.fillna('Unknown') # Fill missing values with 'Unknown'

      Name      Age         City Designation
0    Alice     25.0     New York     Unknown
1  Unknown     30.0  Los Angeles     Manager
2  Charlie  Unknown      Unknown     Analyst
3    David     40.0      Unknown    Director

In [15]:
values = {'Name': 'Unknown', 'Age': df['Age'].mean(), 'City': 'Unknown', 'Designation': 'Unknown'}
df.fillna(value=values) # Fill missing values with specified values

      Name        Age         City Designation
0    Alice  25.000000     New York     Unknown
1  Unknown  30.000000  Los Angeles     Manager
2  Charlie  31.666667      Unknown     Analyst
3    David  40.000000      Unknown    Director