## Operations on DataFrames

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df.shape # dimensions of the dataframe(matrix)

(5, 3)

In [5]:
df.describe() # statistical summary of the dataframe

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
df.info # summary of the dataframe, including data types and non-null counts

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [10]:
df['A'] *2 # element-wise multiplication of column 'A' by 2

0     2
1     4
2     6
3     8
4    10
Name: A, dtype: int64

In [16]:
df['D'] = df["B"].apply(lambda x : x**2)
df

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500